### PR TITLE
Add Japanese documents

### PR DESCRIPTION
**Pull request by fisuda**

### CODE REVIEW

**Comment by taliaga** [comment]
Hi @fisuda thank you so much for this and the other 2 Pull Requests with the translations! For sure it must have been a hard work. 

I'm happy to merge all these branches (my japanese knowledge is Nul,  so I won't be able to catch typos and things like that :p) However, I'd like to first discuss with you what's the best way to get this merged without incurring in complications. I mainly have 3 questions, not sure which are the best answers yet, but let's figure them out.

1- I'd rather not duplicate the yaml, shellscripts and config files. Would you agree? Shall we keep your translated markdowns side-to-side with the English ones?

2- Readthedocs still has no official guidelines for Markdown translations (that I'm aware of). So, what I'm wondering is, how could we "render" your translations for the japanese readers in the meantime?

3- Finally, how could we make sure we have the least divergence as English documentation evolves?. Shall we notify/flag someone/something as English docs are adjusted?

**Comment by fisuda** [comment]
Hi @taliaga,

Sorry for the late reply. Thanks for your comment.

1. I agree. I contibute only .md files translated to Japanese. As there are many .md files, I think that it is better to put them on another folder.

2. May I host .md files on my website? 
   Ex. https://smartsdk-guided-tour.letsfiware.jp/

3. In case it is necessary to update Japanese documents, could you please open an new issue on github? When I find it, I will translate it as soon as possible.(I wish that another Japanese contributer increase.)

**Comment by taliaga** [comment]
Great! 
1. So let's keep the `ja` folder but only with markdown files and remove the duplicated `yml` and config files from there.
1. Absolutely! I guess with such page in place we don't need to worry about readthedoc's multilang support at this moment.
1. OK that sounds good. (Hopefully there will be more translators). I'll open the issue and keep on linking to it when I see changes that require a translation update, so that changes can be batched a bit before undergoing the effort of translation.

Thank you again!

**Comment by fisuda** [comment]
Thank you for your understanding.
I will retry sending PR with only markdown files.

**Comment by fisuda** [comment]
I removed the yaml, shellscripts and config files. Please check PR again.

**Comment by taliaga** [comment]
Same heads-up in this one regarding linting for next time.
Thanks!

**Review by taliaga — APPROVED** [review]

**Comment by fisuda** [comment]
Thank you for taking your time for my PR. 
I will check the lint messages.

**Pull request merged**
